-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then
  vim.cmd('highlight clear')
end
vim.g.colors_name = 'iofq'

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, '@attribute', { link = 'Constant' })
hi(0, '@character.special', { link = 'SpecialChar' })
hi(0, '@comment.error', { bg = '#e85c51', fg = '#152528' })
hi(0, '@comment.note', { bg = '#5a93aa', fg = '#152528' })
hi(0, '@comment.todo', { bg = '#7aa4a1', fg = '#152528' })
hi(0, '@comment.warning', { bg = '#fda47f', fg = '#152528' })
hi(0, '@conditional', { link = 'Conditional' })
hi(0, '@constant.builtin', { fg = '#ff9664' })
hi(0, '@constant.macro', { link = 'Macro' })
hi(0, '@constructor', { fg = '#a1cdd8' })
hi(0, '@constructor.lua', { fg = '#cbd9d8' })
hi(0, '@diff.delta', { link = 'diffChanged' })
hi(0, '@diff.minus', { link = 'diffRemoved' })
hi(0, '@diff.plus', { link = 'diffAdded' })
hi(0, '@exception', { link = 'Exception' })
hi(0, '@field', { fg = '#5a93aa' })
hi(0, '@field.rust', { fg = '#cbd9d8' })
hi(0, '@float', { link = 'Float' })
hi(0, '@function.builtin', { fg = '#e85c51' })
hi(0, '@function.macro', { fg = '#e85c51' })
hi(0, '@include', { link = 'Include' })
hi(0, '@keyword.conditional', { link = 'Conditional' })
hi(0, '@keyword.conditional.ternary', { link = 'Conditional' })
hi(0, '@keyword.exception', { link = 'Exception' })
hi(0, '@keyword.function', { fg = '#ad5c7c' })
hi(0, '@keyword.import', { link = 'Include' })
hi(0, '@keyword.operator', { fg = '#cbd9d8' })
hi(0, '@keyword.repeat', { link = 'Repeat' })
hi(0, '@keyword.return', { fg = '#e85c51' })
hi(0, '@keyword.storage', { link = 'StorageClass' })
hi(0, '@label.json', { fg = '#73a3b7' })
hi(0, '@lsp.type.boolean', { link = '@boolean' })
hi(0, '@lsp.type.builtinType', { link = '@type.builtin' })
hi(0, '@lsp.type.comment', { link = '@comment' })
hi(0, '@lsp.type.enum', { link = '@type' })
hi(0, '@lsp.type.enumMember', { link = '@constant' })
hi(0, '@lsp.type.escapeSequence', { link = '@string.escape' })
hi(0, '@lsp.type.formatSpecifier', { link = '@punctuation.special' })
hi(0, '@lsp.type.interface', { fg = '#eb746b' })
hi(0, '@lsp.type.keyword', { link = '@keyword' })
hi(0, '@lsp.type.namespace', { link = '@module' })
hi(0, '@lsp.type.number', { link = '@number' })
hi(0, '@lsp.type.operator', { link = '@operator' })
hi(0, '@lsp.type.parameter', { link = '@parameter' })
hi(0, '@lsp.type.property', { link = '@property' })
hi(0, '@lsp.type.selfKeyword', { link = '@variable.builtin' })
hi(0, '@lsp.type.typeAlias', { link = '@type.definition' })
hi(0, '@lsp.type.unresolvedReference', { link = '@error' })
hi(0, '@lsp.type.variable', {})
hi(0, '@lsp.typemod.class.defaultLibrary', { link = '@type.builtin' })
hi(0, '@lsp.typemod.enum.defaultLibrary', { link = '@type.builtin' })
hi(0, '@lsp.typemod.enumMember.defaultLibrary', { link = '@constant.builtin' })
hi(0, '@lsp.typemod.function.defaultLibrary', { link = '@function.builtin' })
hi(0, '@lsp.typemod.keyword.async', { link = '@keyword.coroutine' })
hi(0, '@lsp.typemod.macro.defaultLibrary', { link = '@function.builtin' })
hi(0, '@lsp.typemod.method.defaultLibrary', { link = '@function.builtin' })
hi(0, '@lsp.typemod.operator.injected', { link = '@operator' })
hi(0, '@lsp.typemod.string.injected', { link = '@string' })
hi(0, '@lsp.typemod.type.defaultLibrary', { link = '@type.builtin' })
hi(0, '@lsp.typemod.variable.defaultLibrary', { link = '@variable.builtin' })
hi(0, '@lsp.typemod.variable.injected', { link = '@variable' })
hi(0, '@markup', { fg = '#e6eaea' })
hi(0, '@markup.heading', { link = 'Title' })
hi(0, '@markup.heading.1.delimiter.vimdoc', { nocombine = true, sp = '#e6eaea', underdouble = true })
hi(0, '@markup.heading.2.delimiter.vimdoc', { nocombine = true, sp = '#e6eaea', underline = true })
hi(0, '@markup.italic', { link = 'Italic' })
hi(0, '@markup.link', { bold = true, fg = '#ad5c7c' })
hi(0, '@markup.link.label', { link = 'Special' })
hi(0, '@markup.link.url', { fg = '#ff9664', italic = true, underline = true })
hi(0, '@markup.list', { fg = '#afd4de' })
hi(0, '@markup.list.checked', { fg = '#7aa4a1' })
hi(0, '@markup.list.unchecked', { fg = '#fda47f' })
hi(0, '@markup.math', { fg = '#73a3b7' })
hi(0, '@markup.quote', { fg = '#cbd9d8' })
hi(0, '@markup.raw', { fg = '#a1cdd8', italic = true })
hi(0, '@markup.raw.block', { fg = '#cb7985' })
hi(0, '@markup.strikethrough', { fg = '#e6eaea', strikethrough = true })
hi(0, '@markup.strong', { bold = true, fg = '#c54e45' })
hi(0, '@markup.underline', { link = 'Underline' })
hi(0, '@module', { fg = '#afd4de' })
hi(0, '@namespace', { fg = '#afd4de' })
hi(0, '@number.float', { link = 'Float' })
hi(0, '@parameter', { fg = '#afd4de' })
hi(0, '@property', { fg = '#5a93aa' })
hi(0, '@punctuation.bracket', { fg = '#cbd9d8' })
hi(0, '@punctuation.delimiter', { fg = '#cbd9d8' })
hi(0, '@punctuation.special', { fg = '#afd4de' })
hi(0, '@repeat', { link = 'Repeat' })
hi(0, '@storageclass', { link = 'StorageClass' })
hi(0, '@string.escape', { bold = true, fg = '#fdb292' })
hi(0, '@string.regex', { fg = '#fdb292' })
hi(0, '@string.regexp', { fg = '#fdb292' })
hi(0, '@string.special', { link = 'Special' })
hi(0, '@string.special.url', { fg = '#ff9664', italic = true, underline = true })
hi(0, '@tag', { fg = '#ad5c7c' })
hi(0, '@tag.attribute', { fg = '#73a3b7', italic = true })
hi(0, '@tag.delimiter', { fg = '#afd4de' })
hi(0, '@text', { fg = '#e6eaea' })
hi(0, '@text.danger', { bg = '#e85c51', fg = '#152528' })
hi(0, '@text.diff.add', { link = 'diffAdded' })
hi(0, '@text.diff.delete', { link = 'diffRemoved' })
hi(0, '@text.emphasis', { link = 'Italic' })
hi(0, '@text.literal', { fg = '#a1cdd8', italic = true })
hi(0, '@text.math', { fg = '#73a3b7' })
hi(0, '@text.note', { bg = '#5a93aa', fg = '#152528' })
hi(0, '@text.reference', { bold = true, fg = '#ad5c7c' })
hi(0, '@text.strike', { fg = '#e6eaea', strikethrough = true })
hi(0, '@text.strong', { bold = true, fg = '#c54e45' })
hi(0, '@text.title', { link = 'Title' })
hi(0, '@text.todo', { bg = '#7aa4a1', fg = '#152528' })
hi(0, '@text.todo.checked', { fg = '#7aa4a1' })
hi(0, '@text.todo.unchecked', { fg = '#fda47f' })
hi(0, '@text.underline', { link = 'Underline' })
hi(0, '@text.warning', { bg = '#fda47f', fg = '#152528' })
hi(0, '@type.builtin', { fg = '#afd4de' })
hi(0, '@variable', { fg = '#ebebeb' })
hi(0, '@variable.builtin', { fg = '#e85c51' })
hi(0, '@variable.member', { fg = '#5a93aa' })
hi(0, '@variable.parameter', { fg = '#afd4de' })
hi(0, 'AerialGuide', { fg = '#2d4f56' })
hi(0, 'AerialLine', { link = 'Search' })
hi(0, 'AlphaButtons', { fg = '#a1cdd8' })
hi(0, 'AlphaFooter', { fg = '#5a93aa' })
hi(0, 'AlphaHeader', { fg = '#73a3b7' })
hi(0, 'AlphaHeaderLabel', { fg = '#ff8349' })
hi(0, 'AlphaShortcut', { fg = '#ff8349' })
hi(0, 'BlinkCmpCursorLineDocumentationHack', { bg = '#254147' })
hi(0, 'BlinkCmpCursorLineMenuHack', { bg = '#425e5e' })
hi(0, 'BlinkCmpDoc', { bg = '#0f1c1e', fg = '#e6eaea' })
hi(0, 'BlinkCmpDocBorder', { bg = '#0f1c1e', fg = '#293e40' })
hi(0, 'BlinkCmpGhostText', { link = 'String' })
hi(0, 'BlinkCmpKindClass', { link = 'Type' })
hi(0, 'BlinkCmpKindConstant', { link = '@constant' })
hi(0, 'BlinkCmpKindConstructor', { link = 'Function' })
hi(0, 'BlinkCmpKindDefault', { fg = '#cbd9d8' })
hi(0, 'BlinkCmpKindEnum', { link = 'Constant' })
hi(0, 'BlinkCmpKindEnumMember', { link = '@field' })
hi(0, 'BlinkCmpKindEvent', { link = 'Constant' })
hi(0, 'BlinkCmpKindField', { link = '@field' })
hi(0, 'BlinkCmpKindFunction', { link = 'Function' })
hi(0, 'BlinkCmpKindInterface', { link = 'Constant' })
hi(0, 'BlinkCmpKindKeyword', { link = 'Identifier' })
hi(0, 'BlinkCmpKindMethod', { link = 'Function' })
hi(0, 'BlinkCmpKindModule', { link = '@namespace' })
hi(0, 'BlinkCmpKindOperator', { link = 'Operator' })
hi(0, 'BlinkCmpKindProperty', { link = '@property' })
hi(0, 'BlinkCmpKindReference', { link = 'Keyword' })
hi(0, 'BlinkCmpKindSnippet', { fg = '#cbd9d8' })
hi(0, 'BlinkCmpKindStruct', { link = 'Type' })
hi(0, 'BlinkCmpKindTypeParameter', { link = '@field' })
hi(0, 'BlinkCmpKindUnit', { link = 'Constant' })
hi(0, 'BlinkCmpKindValue', { link = 'Keyword' })
hi(0, 'BlinkCmpKindVariable', { link = '@variable' })
hi(0, 'BlinkCmpLabel', { fg = '#e6eaea' })
hi(0, 'BlinkCmpLabelDeprecated', { fg = '#587b7b', strikethrough = true })
hi(0, 'BlinkCmpLabelDetail', { link = 'Comment' })
hi(0, 'BlinkCmpLabelMatch', { fg = '#73a3b7' })
hi(0, 'Bold', { bold = true })
hi(0, 'Boolean', { link = 'Number' })
hi(0, 'BufferCurrent', { bg = '#587b7b', fg = '#e6eaea' })
hi(0, 'BufferCurrentIndex', { bg = '#587b7b', fg = '#5a93aa' })
hi(0, 'BufferCurrentMod', { bg = '#587b7b', fg = '#fda47f' })
hi(0, 'BufferCurrentSign', { bg = '#587b7b', fg = '#5a93aa' })
hi(0, 'BufferCurrentTarget', { bg = '#587b7b', fg = '#e85c51' })
hi(0, 'BufferInactive', { bg = '#0f1c1e', fg = '#6d7f8b' })
hi(0, 'BufferInactiveIndex', { bg = '#0f1c1e', fg = '#6d7f8b' })
hi(0, 'BufferInactiveMod', { bg = '#0f1c1e', fg = '#383835' })
hi(0, 'BufferInactiveSign', { bg = '#0f1c1e', fg = '#254147' })
hi(0, 'BufferInactiveTarget', { bg = '#0f1c1e', fg = '#e85c51' })
hi(0, 'BufferTabpage', { bg = '#0f1c1e', fg = '#254147' })
hi(0, 'BufferTabpages', { bg = '#0f1c1e' })
hi(0, 'BufferVisible', { bg = '#0f1c1e', fg = '#e6eaea' })
hi(0, 'BufferVisibleIndex', { bg = '#0f1c1e', fg = '#5a93aa' })
hi(0, 'BufferVisibleMod', { bg = '#0f1c1e', fg = '#fda47f' })
hi(0, 'BufferVisibleSign', { bg = '#0f1c1e', fg = '#5a93aa' })
hi(0, 'BufferVisibleTarget', { bg = '#0f1c1e', fg = '#e85c51' })
hi(0, 'Character', { link = 'String' })
hi(0, 'CmpDocumentation', { bg = '#0f1c1e', fg = '#e6eaea' })
hi(0, 'CmpDocumentationBorder', { bg = '#0f1c1e', fg = '#293e40' })
hi(0, 'CmpItemAbbr', { fg = '#e6eaea' })
hi(0, 'CmpItemAbbrDeprecated', { fg = '#587b7b', strikethrough = true })
hi(0, 'CmpItemAbbrMatch', { fg = '#73a3b7' })
hi(0, 'CmpItemAbbrMatchFuzzy', { fg = '#73a3b7' })
hi(0, 'CmpItemKindClass', { link = 'Type' })
hi(0, 'CmpItemKindConstant', { link = '@constant' })
hi(0, 'CmpItemKindConstructor', { link = 'Function' })
hi(0, 'CmpItemKindDefault', { fg = '#cbd9d8' })
hi(0, 'CmpItemKindEnum', { link = 'Constant' })
hi(0, 'CmpItemKindEnumMember', { link = '@field' })
hi(0, 'CmpItemKindEvent', { link = 'Constant' })
hi(0, 'CmpItemKindField', { link = '@field' })
hi(0, 'CmpItemKindFunction', { link = 'Function' })
hi(0, 'CmpItemKindInterface', { link = 'Constant' })
hi(0, 'CmpItemKindKeyword', { link = 'Identifier' })
hi(0, 'CmpItemKindMethod', { link = 'Function' })
hi(0, 'CmpItemKindModule', { link = '@namespace' })
hi(0, 'CmpItemKindOperator', { link = 'Operator' })
hi(0, 'CmpItemKindProperty', { link = '@property' })
hi(0, 'CmpItemKindReference', { link = 'Keyword' })
hi(0, 'CmpItemKindSnippet', { fg = '#cbd9d8' })
hi(0, 'CmpItemKindStruct', { link = 'Type' })
hi(0, 'CmpItemKindTypeParameter', { link = '@field' })
hi(0, 'CmpItemKindUnit', { link = 'Constant' })
hi(0, 'CmpItemKindValue', { link = 'Keyword' })
hi(0, 'CmpItemKindVariable', { link = '@variable' })
hi(0, 'CmpItemMenu', { link = 'Comment' })
hi(0, 'CocInlayHint', { bg = '#1d3337', fg = '#6d7f8b' })
hi(0, 'ColorColumn', { bg = '#1d3337' })
hi(0, 'Comment', { fg = '#6d7f8b' })
hi(0, 'Conceal', { fg = '#2d4f56' })
hi(0, 'Conditional', { fg = '#b97490' })
hi(0, 'Constant', { fg = '#ff9664' })
hi(0, 'CurSearch', { link = 'IncSearch' })
hi(0, 'Cursor', { bg = '#e6eaea', fg = '#152528' })
hi(0, 'CursorColumn', { link = 'CursorLine' })
hi(0, 'CursorLine', { bg = '#254147' })
hi(0, 'CursorLineNr', { bold = true, fg = '#fda47f' })
hi(0, 'DapUIBreakpointsCurrentLine', { bold = true, fg = '#7aa4a1' })
hi(0, 'DapUIBreakpointsDisabledLine', { fg = '#6d7f8b' })
hi(0, 'DapUIBreakpointsInfo', { fg = '#5a93aa' })
hi(0, 'DapUIBreakpointsLine', { link = 'DapUILineNumber' })
hi(0, 'DapUIBreakpointsPath', { fg = '#afd4de' })
hi(0, 'DapUIDecoration', { fg = '#587b7b' })
hi(0, 'DapUIFloatBorder', { link = 'FloatBorder' })
hi(0, 'DapUIFrameName', { link = 'Normal' })
hi(0, 'DapUILineNumber', { link = 'Number' })
hi(0, 'DapUIModifiedValue', { bold = true, fg = '#ebebeb' })
hi(0, 'DapUIScope', { fg = '#afd4de' })
hi(0, 'DapUISource', { link = 'Keyword' })
hi(0, 'DapUIStoppedThread', { fg = '#afd4de' })
hi(0, 'DapUIThread', { link = 'String' })
hi(0, 'DapUIType', { link = 'Type' })
hi(0, 'DapUIValue', { fg = '#ebebeb' })
hi(0, 'DapUIVariable', { fg = '#ebebeb' })
hi(0, 'DapUIWatchesEmpty', { fg = '#e85c51' })
hi(0, 'DapUIWatchesError', { fg = '#e85c51' })
hi(0, 'DapUIWatchesValue', { fg = '#fda47f' })
hi(0, 'DashboardCenter', { link = 'String' })
hi(0, 'DashboardFooter', { fg = '#ff9664', italic = true })
hi(0, 'DashboardHeader', { link = 'Title' })
hi(0, 'DashboardShortCut', { link = 'Identifier' })
hi(0, 'Delimiter', { link = 'Special' })
hi(0, 'DiagnosticError', { fg = '#e85c51' })
hi(0, 'DiagnosticHint', { fg = '#7aa4a1' })
hi(0, 'DiagnosticInfo', { fg = '#5a93aa' })
hi(0, 'DiagnosticOk', { fg = '#7aa4a1' })
hi(0, 'DiagnosticUnderlineError', { sp = '#e85c51', undercurl = true })
hi(0, 'DiagnosticUnderlineHint', { sp = '#7aa4a1', undercurl = true })
hi(0, 'DiagnosticUnderlineInfo', { sp = '#5a93aa', undercurl = true })
hi(0, 'DiagnosticUnderlineOk', { sp = '#7aa4a1', undercurl = true })
hi(0, 'DiagnosticUnderlineWarn', { sp = '#fda47f', undercurl = true })
hi(0, 'DiagnosticVirtualTextError', { bg = '#352d2e', fg = '#e85c51' })
hi(0, 'DiagnosticVirtualTextHint', { bg = '#24383a', fg = '#7aa4a1' })
hi(0, 'DiagnosticVirtualTextInfo', { bg = '#1f353c', fg = '#5a93aa' })
hi(0, 'DiagnosticVirtualTextOk', { bg = '#24383a', fg = '#7aa4a1' })
hi(0, 'DiagnosticVirtualTextWarn', { bg = '#383835', fg = '#fda47f' })
hi(0, 'DiagnosticWarn', { fg = '#fda47f' })
hi(0, 'DiffAdd', { bg = '#293e40' })
hi(0, 'DiffChange', { bg = '#31474b' })
hi(0, 'DiffDelete', { bg = '#4a3332' })
hi(0, 'DiffText', { bg = '#466066' })
hi(0, 'DiffviewDiffAddAsDelete', { bg = '#4a3332' })
hi(0, 'DiffviewDim1', { fg = '#6d7f8b' })
hi(0, 'DiffviewFilePanelCounter', { bold = true, fg = '#a1cdd8' })
hi(0, 'DiffviewFilePanelFileName', { fg = '#e6eaea' })
hi(0, 'DiffviewFilePanelTitle', { bold = true, fg = '#b97490' })
hi(0, 'DiffviewPrimary', { fg = '#73a3b7' })
hi(0, 'DiffviewSecondary', { fg = '#7aa4a1' })
hi(0, 'Directory', { fg = '#73a3b7' })
hi(0, 'EndOfBuffer', { fg = '#152528' })
hi(0, 'Error', { fg = '#e85c51' })
hi(0, 'ErrorMsg', { fg = '#e85c51' })
hi(0, 'Exception', { link = 'Keyword' })
hi(0, 'EyelinerDimmed', { fg = '#6d7f8b' })
hi(0, 'EyelinerPrimary', { underline = true })
hi(0, 'EyelinerSecondary', { bold = true, underline = true })
hi(0, 'FernBranchText', { fg = '#5a93aa' })
hi(0, 'FidgetTask', { link = 'LineNr' })
hi(0, 'FidgetTitle', { link = 'Title' })
hi(0, 'FloatBorder', { fg = '#587b7b' })
hi(0, 'FocusedSymbol', { link = 'Search' })
hi(0, 'FoldColumn', { fg = '#587b7b' })
hi(0, 'Folded', { bg = '#1d3337', fg = '#587b7b' })
hi(0, 'Function', { fg = '#73a3b7' })
hi(0, 'GitGutterAdd', { fg = '#7aa4a1' })
hi(0, 'GitGutterChange', { fg = '#fda47f' })
hi(0, 'GitGutterDelete', { fg = '#e85c51' })
hi(0, 'GitSignsAdd', { fg = '#7aa4a1' })
hi(0, 'GitSignsChange', { fg = '#fda47f' })
hi(0, 'GitSignsDelete', { fg = '#e85c51' })
hi(0, 'GlyphPalette0', { fg = '#2f3239' })
hi(0, 'GlyphPalette1', { fg = '#e85c51' })
hi(0, 'GlyphPalette10', { fg = '#8eb2af' })
hi(0, 'GlyphPalette11', { fg = '#fdb292' })
hi(0, 'GlyphPalette12', { fg = '#73a3b7' })
hi(0, 'GlyphPalette13', { fg = '#b97490' })
hi(0, 'GlyphPalette14', { fg = '#afd4de' })
hi(0, 'GlyphPalette15', { fg = '#eeeeee' })
hi(0, 'GlyphPalette2', { fg = '#7aa4a1' })
hi(0, 'GlyphPalette3', { fg = '#fda47f' })
hi(0, 'GlyphPalette4', { fg = '#5a93aa' })
hi(0, 'GlyphPalette5', { fg = '#ad5c7c' })
hi(0, 'GlyphPalette6', { fg = '#a1cdd8' })
hi(0, 'GlyphPalette7', { fg = '#eeeeee' })
hi(0, 'GlyphPalette8', { fg = '#4e5157' })
hi(0, 'GlyphPalette9', { fg = '#eb746b' })
hi(0, 'HopNextKey', { bold = true, fg = '#a1cdd8' })
hi(0, 'HopNextKey1', { bold = true, fg = '#5a93aa' })
hi(0, 'HopNextKey2', { fg = '#4d7d90' })
hi(0, 'HopUnmatched', { fg = '#6d7f8b' })
hi(0, 'Identifier', { fg = '#a1cdd8' })
hi(0, 'IncSearch', { bg = '#7aa4a1', fg = '#152528' })
hi(0, 'IndentBlanklineChar', { fg = '#254147' })
hi(0, 'IndentBlanklineContextChar', { fg = '#ebebeb' })
hi(0, 'IndentBlanklineContextStart', { sp = '#ebebeb', underline = true })
hi(0, 'IndentBlanklineIndent1', { fg = '#cb7985' })
hi(0, 'IndentBlanklineIndent2', { fg = '#5a93aa' })
hi(0, 'IndentBlanklineIndent3', { fg = '#ff8349' })
hi(0, 'IndentBlanklineIndent4', { fg = '#a1cdd8' })
hi(0, 'IndentBlanklineIndent5', { fg = '#e85c51' })
hi(0, 'IndentBlanklineIndent6', { fg = '#fda47f' })
hi(0, 'Italic', { italic = true })
hi(0, 'Keyword', { fg = '#ad5c7c' })
hi(0, 'Label', { link = 'Conditional' })
hi(0, 'LazyButtonActive', { link = 'TabLineSel' })
hi(0, 'LazyDimmed', { link = 'LineNr' })
hi(0, 'LazyProp', { link = 'LineNr' })
hi(0, 'LeapBackdrop', { fg = '#6d7f8b' })
hi(0, 'LeapLabelPrimary', { bg = '#d38d97', fg = '#152528' })
hi(0, 'LeapLabelSecondary', { bg = '#afd4de', fg = '#152528' })
hi(0, 'LeapMatch', { bg = '#d38d97', fg = '#152528' })
hi(0, 'LightspeedGreyWash', { fg = '#6d7f8b' })
hi(0, 'LineNr', { fg = '#587b7b' })
hi(0, 'LspCodeLens', { fg = '#6d7f8b' })
hi(0, 'LspCodeLensSeparator', { fg = '#587b7b' })
hi(0, 'LspFloatWinBorder', { fg = '#587b7b' })
hi(0, 'LspFloatWinNormal', { bg = '#0f1c1e' })
hi(0, 'LspInlayHint', { bg = '#1d3337', fg = '#6d7f8b' })
hi(0, 'LspReferenceRead', { bg = '#293e40' })
hi(0, 'LspReferenceText', { bg = '#293e40' })
hi(0, 'LspReferenceWrite', { bg = '#293e40' })
hi(0, 'LspSagaBorderTitle', { link = 'Title' })
hi(0, 'LspSagaCodeActionBorder', { fg = '#587b7b' })
hi(0, 'LspSagaCodeActionContent', { link = 'String' })
hi(0, 'LspSagaCodeActionTitle', { link = 'Title' })
hi(0, 'LspSagaDefPreviewBorder', { fg = '#587b7b' })
hi(0, 'LspSagaFinderSelection', { fg = '#293e40' })
hi(0, 'LspSagaHoverBorder', { fg = '#587b7b' })
hi(0, 'LspSagaRenameBorder', { fg = '#587b7b' })
hi(0, 'LspSagaSignatureHelpBorder', { fg = '#e85c51' })
hi(0, 'LspSignatureActiveParameter', { fg = '#425e5e' })
hi(0, 'LspTroubleCount', { bg = '#587b7b', fg = '#ad5c7c' })
hi(0, 'LspTroubleNormal', { bg = '#0f1c1e', fg = '#587b7b' })
hi(0, 'LspTroubleText', { fg = '#cbd9d8' })
hi(0, 'MatchParen', { bold = true, fg = '#fda47f' })
hi(0, 'MiniAnimateCursor', { nocombine = true, reverse = true })
hi(0, 'MiniAnimateNormalFloat', { link = 'NormalFloat' })
hi(0, 'MiniClueBorder', { link = 'FloatBorder' })
hi(0, 'MiniClueDescGroup', { link = 'DiagnosticFloatingWarn' })
hi(0, 'MiniClueDescSingle', { link = 'NormalFloat' })
hi(0, 'MiniClueNextKey', { link = 'DiagnosticFloatingHint' })
hi(0, 'MiniClueNextKeyWithPostkeys', { link = 'DiagnosticFloatingError' })
hi(0, 'MiniClueSeparator', { link = 'DiagnosticFloatingInfo' })
hi(0, 'MiniClueTitle', { link = 'FloatTitle' })
hi(0, 'MiniCompletionActiveParameter', { underline = true })
hi(0, 'MiniCursorword', { link = 'LspReferenceText' })
hi(0, 'MiniCursorwordCurrent', { link = 'LspReferenceText' })
hi(0, 'MiniDepsChangeAdded', { link = 'diffAdded' })
hi(0, 'MiniDepsChangeRemoved', { link = 'diffRemoved' })
hi(0, 'MiniDepsHint', { link = 'DiagnosticHint' })
hi(0, 'MiniDepsInfo', { link = 'DiagnosticInfo' })
hi(0, 'MiniDepsMsgBreaking', { link = 'DiagnosticWarn' })
hi(0, 'MiniDepsPlaceholder', { link = 'Comment' })
hi(0, 'MiniDepsTitle', { link = 'Title' })
hi(0, 'MiniDepsTitleError', { bg = '#e85c51', fg = '#0f1c1e' })
hi(0, 'MiniDepsTitleSame', { link = 'DiffText' })
hi(0, 'MiniDepsTitleUpdate', { bg = '#7aa4a1', fg = '#0f1c1e' })
hi(0, 'MiniDiffOverAdd', { bg = '#31474b' })
hi(0, 'MiniDiffOverChange', { bg = '#466066' })
hi(0, 'MiniDiffOverChangeBuf', { bg = '#466066' })
hi(0, 'MiniDiffOverContext', { bg = '#31474b' })
hi(0, 'MiniDiffOverDelete', { fg = 'red' })
hi(0, 'MiniDiffSignAdd', { fg = 'green', bold = true })
hi(0, 'MiniDiffSignChange', { fg = 'green', bold = true })
hi(0, 'MiniDiffSignDelete', { fg = 'red', bold = true })
hi(0, 'MiniFilesBorder', { link = 'FloatBorder' })
hi(0, 'MiniFilesBorderModified', { link = 'DiagnosticFloatingWarn' })
hi(0, 'MiniFilesCursorLine', { link = 'CursorLine' })
hi(0, 'MiniFilesDirectory', { link = 'Directory' })
hi(0, 'MiniFilesFile', { fg = '#e6eaea' })
hi(0, 'MiniFilesNormal', { link = 'NormalFloat' })
hi(0, 'MiniFilesTitle', { link = 'FloatTitle' })
hi(0, 'MiniFilesTitleFocused', { bold = true, fg = '#e6eaea' })
hi(0, 'MiniHipatternsFixme', { bg = '#e85c51', bold = true, fg = '#0f1c1e' })
hi(0, 'MiniHipatternsHack', { bg = '#fda47f', bold = true, fg = '#0f1c1e' })
hi(0, 'MiniHipatternsNote', { bg = '#5a93aa', bold = true, fg = '#0f1c1e' })
hi(0, 'MiniHipatternsTodo', { bg = '#7aa4a1', bold = true, fg = '#0f1c1e' })
hi(0, 'MiniIconsAzure', { fg = '#73a3b7' })
hi(0, 'MiniIconsBlue', { fg = '#5a93aa' })
hi(0, 'MiniIconsCyan', { fg = '#a1cdd8' })
hi(0, 'MiniIconsGreen', { fg = '#7aa4a1' })
hi(0, 'MiniIconsGrey', { fg = '#eaeeee' })
hi(0, 'MiniIconsOrange', { fg = '#ff8349' })
hi(0, 'MiniIconsPurple', { fg = '#ad5c7c' })
hi(0, 'MiniIconsRed', { fg = '#e85c51' })
hi(0, 'MiniIconsYellow', { fg = '#fda47f' })
hi(0, 'MiniIndentscopePrefix', { nocombine = true })
hi(0, 'MiniIndentscopeSymbol', { link = 'Delimiter' })
hi(0, 'MiniJump', { bg = '#ad5c7c', fg = '#0f1c1e' })
hi(0, 'MiniJump2dDim', { link = 'Comment' })
hi(0, 'MiniJump2dSpot', { bold = true, fg = '#a1cdd8' })
hi(0, 'MiniJump2dSpotAhead', { bg = '#0f1c1e', fg = '#4d7d90', nocombine = true })
hi(0, 'MiniJump2dSpotUnique', { bold = true, fg = '#fda47f' })
hi(0, 'MiniMapNormal', { link = 'NormalFloat' })
hi(0, 'MiniMapSymbolCount', { link = 'Special' })
hi(0, 'MiniMapSymbolLine', { link = 'Title' })
hi(0, 'MiniMapSymbolView', { link = 'Delimiter' })
hi(0, 'MiniNotifyBorder', { link = 'FloatBorder' })
hi(0, 'MiniNotifyNormal', { link = 'NormalFloat' })
hi(0, 'MiniNotifyTitle', { link = 'FloatTitle' })
hi(0, 'MiniOperatorsExchangeFrom', { link = 'IncSearch' })
hi(0, 'MiniPickBorder', { link = 'FloatBorder' })
hi(0, 'MiniPickBorderBusy', { link = 'DiagnosticFloatingWarn' })
hi(0, 'MiniPickBorderText', { link = 'FloatTitle' })
hi(0, 'MiniPickHeader', { link = 'DiagnosticFloatingHint' })
hi(0, 'MiniPickIconDirectory', { link = 'Directory' })
hi(0, 'MiniPickIconFile', { link = 'MiniPickNormal' })
hi(0, 'MiniPickMatchCurrent', { link = 'CursorLine' })
hi(0, 'MiniPickMatchMarked', { link = 'Visual' })
hi(0, 'MiniPickMatchRanges', { link = 'DiagnosticFloatingHint' })
hi(0, 'MiniPickNormal', { link = 'NormalFloat' })
hi(0, 'MiniPickPreviewLine', { link = 'CursorLine' })
hi(0, 'MiniPickPreviewRegion', { link = 'IncSearch' })
hi(0, 'MiniPickPrompt', { link = 'DiagnosticFloatingInfo' })
hi(0, 'MiniStarterCurrent', { nocombine = true })
hi(0, 'MiniStarterFooter', { fg = '#ff9664', italic = true })
hi(0, 'MiniStarterHeader', { link = 'Title' })
hi(0, 'MiniStarterInactive', { link = 'Comment' })
hi(0, 'MiniStarterItem', { link = 'Normal' })
hi(0, 'MiniStarterItemBullet', { fg = '#587b7b' })
hi(0, 'MiniStarterItemPrefix', { fg = '#cb7985' })
hi(0, 'MiniStarterQuery', { fg = '#7aa4a1' })
hi(0, 'MiniStarterSection', { fg = '#e85c51' })
hi(0, 'MiniStatuslineDevinfo', { bg = '#1d3337', fg = '#cbd9d8' })
hi(0, 'MiniStatuslineFileinfo', { bg = '#1d3337', fg = '#cbd9d8' })
hi(0, 'MiniStatuslineFilename', { link = 'StatusLine' })
hi(0, 'MiniStatuslineInactive', { link = 'StatusLineNC' })
hi(0, 'MiniStatuslineModeCommand', { bg = '#fda47f', bold = true, fg = '#0f1c1e' })
hi(0, 'MiniStatuslineModeInsert', { bg = '#7aa4a1', bold = true, fg = '#0f1c1e' })
hi(0, 'MiniStatuslineModeNormal', { bg = '#a1cdd8', bold = true, fg = '#0f1c1e' })
hi(0, 'MiniStatuslineModeOther', { bg = '#5a93aa', bold = true, fg = '#0f1c1e' })
hi(0, 'MiniStatuslineModeReplace', { bg = '#e85c51', bold = true, fg = '#0f1c1e' })
hi(0, 'MiniStatuslineModeVisual', { bg = '#ad5c7c', bold = true, fg = '#0f1c1e' })
hi(0, 'MiniSurround', { link = 'IncSearch' })
hi(0, 'MiniTablineCurrent', { bg = '#2d4f56', bold = true, fg = '#cbd9d8' })
hi(0, 'MiniTablineFill', { link = 'TabLineFill' })
hi(0, 'MiniTablineHidden', { bg = '#1d3337', fg = '#587b7b' })
hi(0, 'MiniTablineModifiedCurrent', { bg = '#cbd9d8', bold = true, fg = '#2d4f56' })
hi(0, 'MiniTablineModifiedHidden', { bg = '#587b7b', fg = '#1d3337' })
hi(0, 'MiniTablineModifiedVisible', { bg = '#cbd9d8', fg = '#1d3337' })
hi(0, 'MiniTablineTabpagesection', { bg = '#152528', bold = true, fg = '#e6eaea' })
hi(0, 'MiniTablineVisible', { bg = '#1d3337', fg = '#cbd9d8' })
hi(0, 'MiniTestEmphasis', { bold = true })
hi(0, 'MiniTestFail', { bold = true, fg = '#e85c51' })
hi(0, 'MiniTestPass', { bold = true, fg = '#7aa4a1' })
hi(0, 'MiniTrailspace', { bg = '#e85c51' })
hi(0, 'ModeMsg', { bold = true, fg = '#fda47f' })
hi(0, 'ModesCopy', { bg = '#fda47f' })
hi(0, 'ModesDelete', { bg = '#e85c51' })
hi(0, 'ModesInsert', { bg = '#a1cdd8' })
hi(0, 'ModesVisual', { bg = '#ad5c7c' })
hi(0, 'MoreMsg', { bold = true, fg = '#5a93aa' })
hi(0, 'NagicIconsOperator', { link = 'Operator' })
hi(0, 'NavicIconsBoolean', { link = 'Boolean' })
hi(0, 'NavicIconsClass', { link = 'Type' })
hi(0, 'NavicIconsConstant', { link = 'Constant' })
hi(0, 'NavicIconsConstructor', { link = 'Function' })
hi(0, 'NavicIconsEnum', { link = 'Constant' })
hi(0, 'NavicIconsEnumMember', { link = '@field' })
hi(0, 'NavicIconsEvent', { link = 'Constant' })
hi(0, 'NavicIconsField', { link = '@field' })
hi(0, 'NavicIconsFile', { link = 'Directory' })
hi(0, 'NavicIconsFunction', { link = 'Function' })
hi(0, 'NavicIconsInterface', { link = 'Constant' })
hi(0, 'NavicIconsKey', { link = 'Identifier' })
hi(0, 'NavicIconsMethod', { link = 'Function' })
hi(0, 'NavicIconsModule', { link = '@namespace' })
hi(0, 'NavicIconsNamespace', { link = '@namespace' })
hi(0, 'NavicIconsNull', { link = 'Type' })
hi(0, 'NavicIconsNumber', { link = 'Number' })
hi(0, 'NavicIconsObject', { link = '@namespace' })
hi(0, 'NavicIconsPackage', { link = '@namespace' })
hi(0, 'NavicIconsProperty', { link = '@property' })
hi(0, 'NavicIconsString', { link = 'String' })
hi(0, 'NavicIconsStruct', { link = 'Type' })
hi(0, 'NavicIconsTypeParameter', { link = '@field' })
hi(0, 'NavicIconsVariable', { link = '@variable' })
hi(0, 'NavicSeparator', { fg = '#2d4f56' })
hi(0, 'NavicText', { fg = '#e6eaea' })
hi(0, 'NeoTreeDimText', { link = 'Conceal' })
hi(0, 'NeoTreeDirectoryIcon', { fg = '#5a93aa' })
hi(0, 'NeoTreeDirectoryName', { fg = '#5a93aa' })
hi(0, 'NeoTreeDotfile', { fg = '#4d7d90' })
hi(0, 'NeoTreeFileName', { fg = '#cbd9d8' })
hi(0, 'NeoTreeFileNameOpened', { fg = '#e6eaea' })
hi(0, 'NeoTreeGitAdded', { fg = '#7aa4a1' })
hi(0, 'NeoTreeGitConflict', { fg = '#ff8349', italic = true })
hi(0, 'NeoTreeGitDeleted', { fg = '#e85c51' })
hi(0, 'NeoTreeGitIgnored', { fg = '#6d7f8b' })
hi(0, 'NeoTreeGitModified', { fg = '#fda47f' })
hi(0, 'NeoTreeGitUntracked', { fg = '#934e69' })
hi(0, 'NeoTreeIndentMarker', { fg = '#2d4f56' })
hi(0, 'NeoTreeNormal', { fg = '#e6eaea' })
hi(0, 'NeoTreeNormalNC', { link = 'NeoTreeNormal' })
hi(0, 'NeoTreeRootName', { bold = true, fg = '#ff8349' })
hi(0, 'NeoTreeSymbolicLinkTarget', { fg = '#ad6771' })
hi(0, 'NeogitBranch', { fg = '#fda47f' })
hi(0, 'NeogitDiffAdd', { fg = '#7aa4a1' })
hi(0, 'NeogitDiffAddHighlight', { bg = '#293e40' })
hi(0, 'NeogitDiffContextHighlight', { bg = '#1d3337' })
hi(0, 'NeogitDiffDelete', { fg = '#e85c51' })
hi(0, 'NeogitDiffDeleteHighlight', { bg = '#4a3332' })
hi(0, 'NeogitHunkHeader', { bg = '#254147', fg = '#5a93aa' })
hi(0, 'NeogitHunkHeaderHighlight', { bg = '#293e40', fg = '#5a93aa' })
hi(0, 'NeogitNotificationError', { fg = '#e85c51' })
hi(0, 'NeogitNotificationInfo', { fg = '#5a93aa' })
hi(0, 'NeogitNotificationWarning', { fg = '#fda47f' })
hi(0, 'NeogitRemote', { fg = '#7aa4a1' })
hi(0, 'NeotestAdapterName', { bold = true, fg = '#cb7985' })
hi(0, 'NeotestDir', { fg = '#a1cdd8' })
hi(0, 'NeotestExpandMarker', { link = 'Conceal' })
hi(0, 'NeotestFailed', { fg = '#e85c51' })
hi(0, 'NeotestFile', { fg = '#5a93aa' })
hi(0, 'NeotestFocused', { underline = true })
hi(0, 'NeotestIndent', { link = 'Conceal' })
hi(0, 'NeotestMarked', { bold = true, fg = '#e6eaea' })
hi(0, 'NeotestNamespace', { fg = '#89aeb8' })
hi(0, 'NeotestPassed', { fg = '#7aa4a1' })
hi(0, 'NeotestRunning', { fg = '#ff8349' })
hi(0, 'NeotestSkipped', { fg = '#fda47f' })
hi(0, 'NeotestTest', { link = 'Normal' })
hi(0, 'NonText', { fg = '#2d4f56' })
hi(0, 'Normal', { fg = '#e6eaea' })
hi(0, 'NormalFloat', { bg = '#0f1c1e', fg = '#e6eaea' })
hi(0, 'NormalNC', { fg = '#e6eaea' })
hi(0, 'NotifyBackground', { link = 'NormalFloat' })
hi(0, 'NotifyDEBUGBorder', { fg = '#486565' })
hi(0, 'NotifyDEBUGIcon', { link = 'NotifyDEBUGTitle' })
hi(0, 'NotifyDEBUGTitle', { fg = '#7aa4a1' })
hi(0, 'NotifyERRORBorder', { fg = '#7e413d' })
hi(0, 'NotifyERRORIcon', { link = 'NotifyERRORTitle' })
hi(0, 'NotifyERRORTitle', { fg = '#e85c51' })
hi(0, 'NotifyINFOBorder', { fg = '#385c69' })
hi(0, 'NotifyINFOIcon', { link = 'NotifyINFOTitle' })
hi(0, 'NotifyINFOTitle', { fg = '#5a93aa' })
hi(0, 'NotifyTRACEBorder', { fg = '#2d4f56' })
hi(0, 'NotifyTRACEIcon', { link = 'NotifyTRACETitle' })
hi(0, 'NotifyTRACETitle', { fg = '#6d7f8b' })
hi(0, 'NotifyWARNBorder', { fg = '#896554' })
hi(0, 'NotifyWARNIcon', { link = 'NotifyWARNTitle' })
hi(0, 'NotifyWARNTitle', { fg = '#fda47f' })
hi(0, 'Number', { fg = '#ff8349' })
hi(0, 'NvimTreeEmptyFolderName', { fg = '#587b7b' })
hi(0, 'NvimTreeFolderIcon', { fg = '#5a93aa' })
hi(0, 'NvimTreeFolderName', { fg = '#5a93aa' })
hi(0, 'NvimTreeGitDeleted', { fg = '#e85c51' })
hi(0, 'NvimTreeGitDirty', { fg = '#fda47f' })
hi(0, 'NvimTreeGitMerge', { fg = '#ff8349' })
hi(0, 'NvimTreeGitNew', { fg = '#7aa4a1' })
hi(0, 'NvimTreeGitRenamed', { link = 'NvimTreeGitDeleted' })
hi(0, 'NvimTreeGitStaged', { link = 'NvimTreeGitStaged' })
hi(0, 'NvimTreeImageFile', { fg = '#c8c8c8' })
hi(0, 'NvimTreeIndentMarker', { fg = '#2d4f56' })
hi(0, 'NvimTreeNormal', { fg = '#e6eaea' })
hi(0, 'NvimTreeOpenedFile', { fg = '#d38d97' })
hi(0, 'NvimTreeOpenedFolderName', { fg = '#73a3b7' })
hi(0, 'NvimTreeRootFolder', { bold = true, fg = '#ff8349' })
hi(0, 'NvimTreeSpecialFile', { fg = '#a1cdd8' })
hi(0, 'NvimTreeSymlink', { fg = '#ad6771' })
hi(0, 'NvimTreeVertSplit', { link = 'VertSplit' })
hi(0, 'Operator', { fg = '#cbd9d8' })
hi(0, 'Pmenu', { bg = '#293e40', fg = '#e6eaea' })
hi(0, 'PmenuSel', { bg = '#425e5e' })
hi(0, 'PmenuThumb', { bg = '#425e5e' })
hi(0, 'PounceAccept', { bg = '#ff9664', fg = '#152528' })
hi(0, 'PounceAcceptBest', { bg = '#afd4de', fg = '#152528' })
hi(0, 'PounceGap', { bg = '#293e40', fg = '#e6eaea' })
hi(0, 'PounceMatch', { bg = '#425e5e', fg = '#e6eaea' })
hi(0, 'PreProc', { fg = '#d38d97' })
hi(0, 'Question', { link = 'MoreMsg' })
hi(0, 'QuickFixLine', { link = 'CursorLine' })
hi(0, 'RainbowDelimiterBlue', { fg = '#5a93aa' })
hi(0, 'RainbowDelimiterCyan', { fg = '#a1cdd8' })
hi(0, 'RainbowDelimiterGreen', { fg = '#7aa4a1' })
hi(0, 'RainbowDelimiterOrange', { fg = '#ff8349' })
hi(0, 'RainbowDelimiterPurple', { fg = '#ad5c7c' })
hi(0, 'RainbowDelimiterRed', { fg = '#e85c51' })
hi(0, 'RainbowDelimiterYellow', { fg = '#fda47f' })
hi(0, 'Repeat', { link = 'Conditional' })
hi(0, 'Search', { bg = '#425e5e', fg = '#e6eaea' })
hi(0, 'SignColumn', { fg = '#587b7b' })
hi(0, 'SignColumnSB', { link = 'SignColumn' })
hi(0, 'SignifySignAdd', { fg = '#7aa4a1' })
hi(0, 'SignifySignChange', { fg = '#fda47f' })
hi(0, 'SignifySignDelete', { fg = '#e85c51' })
hi(0, 'SnacksBackdrop', { bg = '#000000' })
hi(0, 'SnacksImageMath', { fg = '#73a3b7' })
hi(0, 'SnacksPickerDir', { fg = '#cccccc' })
hi(0, 'Sneak', { bg = '#ad5c7c', fg = '#0f1c1e' })
hi(0, 'SneakScope', { bg = '#293e40' })
hi(0, 'Special', { fg = '#73a3b7' })
hi(0, 'SpecialKey', { link = 'NonText' })
hi(0, 'SpellBad', { sp = '#e85c51', undercurl = true })
hi(0, 'SpellCap', { sp = '#fda47f', undercurl = true })
hi(0, 'SpellLocal', { sp = '#5a93aa', undercurl = true })
hi(0, 'SpellRare', { sp = '#5a93aa', undercurl = true })
hi(0, 'Statement', { fg = '#ad5c7c' })
hi(0, 'StatusLine', { bg = 'none' })
hi(0, 'StatusLineNC', { bg = 'none' })
hi(0, 'String', { fg = '#7aa4a1' })
hi(0, 'Substitute', { bg = '#e85c51', fg = '#152528' })
hi(0, 'SymbolOutlineConnector', { link = 'Conceal' })
hi(0, 'TSRainbowBlue', { fg = '#5a93aa' })
hi(0, 'TSRainbowCyan', { fg = '#a1cdd8' })
hi(0, 'TSRainbowGreen', { fg = '#7aa4a1' })
hi(0, 'TSRainbowOrange', { fg = '#ff8349' })
hi(0, 'TSRainbowRed', { fg = '#e85c51' })
hi(0, 'TSRainbowViolet', { fg = '#ad5c7c' })
hi(0, 'TSRainbowYellow', { fg = '#fda47f' })
hi(0, 'TabLine', { bg = '#1d3337', fg = '#cbd9d8' })
hi(0, 'TablineFill', { bg = 'none' })
hi(0, 'TabLineSel', { bg = '#587b7b', fg = '#152528' })
hi(0, 'TelescopeBorder', { fg = '#2d4f56' })
hi(0, 'TelescopeMatching', { link = 'Search' })
hi(0, 'TelescopeSelection', { link = 'CursorLine' })
hi(0, 'TelescopeSelectionCaret', { fg = '#7aa4a1' })
hi(0, 'Title', { bold = true, fg = '#73a3b7' })
hi(0, 'Todo', { bg = '#5a93aa', fg = '#152528' })
hi(0, 'Type', { fg = '#fda47f' })
hi(0, 'Visual', { bg = '#293e40' })
hi(0, 'WarningMsg', { fg = '#fda47f' })
hi(0, 'WhichKey', { link = 'Identifier' })
hi(0, 'WhichKeyDesc', { link = 'Keyword' })
hi(0, 'WhichKeyFloat', { link = 'NormalFloat' })
hi(0, 'WhichKeyGroup', { link = 'Function' })
hi(0, 'WhichKeySeparator', { link = 'Comment' })
hi(0, 'WhichKeySeperator', { link = 'Comment' })
hi(0, 'WhichKeyValue', { link = 'Comment' })
hi(0, 'Whitespace', { fg = '#254147' })
hi(0, 'WildMenu', { link = 'Pmenu' })
hi(0, 'WinBar', { bold = true, fg = '#587b7b' })
hi(0, 'WinBarNC', { bold = true, fg = '#587b7b' })
hi(0, 'WinSeparator', { fg = '#0f1c1e' })
hi(0, 'diffAdded', { fg = '#7aa4a1' })
hi(0, 'diffChanged', { fg = '#fda47f' })
hi(0, 'diffFile', { fg = '#5a93aa' })
hi(0, 'diffIndexLine', { fg = '#d38d97' })
hi(0, 'diffLine', { fg = '#ff9664' })
hi(0, 'diffNewFile', { fg = '#7aa4a1' })
hi(0, 'diffOldFile', { fg = '#fda47f' })
hi(0, 'diffRemoved', { fg = '#e85c51' })
hi(0, 'illuminatedWordRead', { link = 'LspReferenceText' })
hi(0, 'illuminatedWordText', { link = 'LspReferenceText' })
hi(0, 'illuminatedWordWrite', { link = 'LspReferenceText' })
hi(0, 'lCursor', { link = 'Cursor' })
hi(0, 'qfFileName', { link = 'Directory' })
hi(0, 'qfLineNr', { link = 'LineNr' })
hi(0, 'rainbowcol1', { fg = '#e85c51' })
hi(0, 'rainbowcol2', { fg = '#fda47f' })
hi(0, 'rainbowcol3', { fg = '#7aa4a1' })
hi(0, 'rainbowcol4', { fg = '#5a93aa' })
hi(0, 'rainbowcol5', { fg = '#a1cdd8' })
hi(0, 'rainbowcol6', { fg = '#ad5c7c' })
hi(0, 'rainbowcol7', { fg = '#cb7985' })
hi(0, 'typescriptParens', { fg = '#cbd9d8' })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = '#2f3239'
g.terminal_color_1 = '#e85c51'
g.terminal_color_2 = '#7aa4a1'
g.terminal_color_3 = '#fda47f'
g.terminal_color_4 = '#5a93aa'
g.terminal_color_5 = '#ad5c7c'
g.terminal_color_6 = '#a1cdd8'
g.terminal_color_7 = '#ebebeb'
g.terminal_color_8 = '#4e5157'
g.terminal_color_9 = '#eb746b'
g.terminal_color_10 = '#8eb2af'
g.terminal_color_11 = '#fdb292'
g.terminal_color_12 = '#73a3b7'
g.terminal_color_13 = '#b97490'
g.terminal_color_14 = '#afd4de'
g.terminal_color_15 = '#eeeeee'
