require('config.globals')
require('config.options')
require('config.keymap')
require('config.autocmd')
require('config.lsp')

require('plugins.tokionight')
require('plugins.lualine')
require('plugins.nvim-cmp')
require('plugins.treesitter')
