name: "Update Nix Flake Inputs"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 1,14 * *"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v20
      - name: Update flake inputs
        id: update
        uses: DeterminateSystems/update-flake-lock@v19
        with:
          pr-title: "chore: update flake.lock"
          commit-msg: "chore: update flake.lock"
          pr-reviewers: iofq
          pr-labels: |
            dependencies
            automated
            auto-merge
      - name: Print PR number
        run: echo Pull request number is ${{ steps.update.outputs.pull-request-number }}.
